version: '3.7'
services:
    redis:
      image: redis:6.0.5
      command: redis-server --requirepass 1234 --port 6379
      container_name: redis
      hostname: redis
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
        
    sample:
      image: mysql:5.7
      restart: always
      command: --lower_case_table_names=1
      container_name: sample
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=sample
        - MYSQL_ROOT_PASSWORD=1234
        - TZ=Asia/Seoul
      command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        - ./mysql/my.cnf:/etc/my.cnf